heat_template_version: 2018-08-31
description: A load-balancer server
resources:
  server:
    type: OS::Nova::Server
    properties:
      name: test-from-heat
      flavor: m1.small
      image: ubuntu-22.04-server-cloudimg-amd64
      key_name: mykey
      user_data: |
        #!/bin/bash

        echo "nameserver 8.8.8.8" > /run/systemd/resolve/stub-resolv.conf
        apt update
        apt -y install nginx
        hostname > /var/www/html/index.nginx-debian.html
      user_data_format: RAW
      networks:
        - subnet: private-subnet
  member:
    type: OS::Octavia::PoolMember
    properties:
      pool: pool1
      address: {get_attr: [server, first_address]}
      protocol_port: 80
      subnet: private-subnet

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
  lb_member:
    description: LB member details.
    value: { get_attr: [member, show] }
