- when: openrc_enable_export
  block:
    - name: Extract the OS_ environment variables
      shell:
        cmd: |
          source {{ openrc_file }} {{ openrc_user }} {{ openrc_project }} &>/dev/null
          env | awk -F= 'BEGIN {print "---" } /^OS_/ { print "  "$1": \""$2"\""} '
      args:
        executable: "/bin/bash"
      register: env_os

    - name: Append the the OS_ environment variables to tox_environment
      set_fact:
        tox_environment: "{{ env_os.stdout|from_yaml|default({})|combine(tox_environment) }}"
